# -*- coding: utf-8 -*-
"""SQL DATABASE IMPORT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wqGY3xgBjrsAfXtT2DnXvmp-X2x71zGW
"""

import pandas as pd

df = pd.read_csv('/sales_datasets.csv')

df.head()

cols = ['c_name','s_code']
df.drop(cols,inplace=True, axis=1)

df.isnull().sum()

df.dtypes

df['order_date']=pd.to_datetime(df['order_date'])

df = df.astype({'qty':'float','price':'float'})

df.dtypes

"""# DataFrame Export

"""

y= []
for  i in range(len(df)):
          x = tuple(df.iloc[i])
          y.append(x)
y

file = open('Sales.txt','w')

for tuple in y:
  file.write(str(tuple)+ ',' + '\n')

file.close()